name: technicalTest
# Version of the service
version:
  major: 1
  minor: 0
  maintenance: 0
server:
  port: 8080
  servlet:
    context-path: /api/${name}/v${version.major}

springdoc:
  packagesToScan: com.jasaban

swagger:
  version: ${version.major}.${version.minor}.${version.maintenance}
  title: technicalTest REST API
  description: Spring Boot REST API. Version ${swagger.version}
  contact:
    name: "José Antonio"
    url: "https://www.linkedin.com/in/jasaban/"
    email: "josame04@gmail.com"

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:technicalTestdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create